### ISSUE TITLE
Characters with multiple readings

### ISSUE THREAD

**Issue by pcdi** [JorisKok/chinese-firefox-quantum#5]
For characters with multiple readings (<span lang="zh">多音字</span>), only one of the readings is shown.

Example: <span lang="zh-Hans">语</span> will be shown only as *yù* “to tell to”, and not as *yǔ* “dialect / language / speech”.

However, there is no problem, if the simplified character in question has two different traditional ones, such as <span lang="zh-Hans">发</span>, which will be correctly shown as *fā* <span lang="zh-Hant">發</span> and *fà* <span lang="zh-Hant">髮</span>.

**Comment by Kottakji** [comment]
Thanks for the example! Will look into it when I have time.

**Comment by Kottakji** [comment]
This should be fixed in version 2.1.4.

**Comment by pcdi** [comment]
I am sorry to reopen this issue, but I noticed that the behavior is still not as expected. The entry for the character 华, for example, shows only two definitions:

* [hua1] /old variant of 花[hua1]/flower/
* [hua2] /magnificent/splendid/flowery/

Whereas the CC–CEDICT contains [six definitions](https://cc-cedict.org/editor/editor.php?handler=QueryDictionary&querydictionary_search=%E5%8D%8E), including variants.

**Comment by Kottakji** [comment]
Hey @pcdi , 
Thanks for the notification. It seems you are correct. Firefox reverted my `2.1.4` to `2.1.3` some time ago. I will have to look into it and resubmit it after making a few changes. Will try to do it somewhere this month.

**Comment by Kottakji** [comment]
@pcdi I've updated the addon. Thanks for pointing out the problem, and giving a helpful example.

Now, you should see 4 entries for 华. The CC-CEDIT shows 6, but 2 of them are variations. I can't support that right now (I would need a lot more time to).

https://cc-cedict.org/editor/editor.php?handler=QueryDictionary&querydictionary_search=%E5%8D%8E

Closing this issue. Please re-open if you think it's not sufficient yet, or open another issue if there are other problems. Cheers.
